version: '3'
# Services Definition
services: 
  # App Service
 app:
   container_name: gin_rest_api_app
   build: 
     context: . # Use image built from the dockerfile in the current directory.
     dockerfile: Dockerfile
   ports: 
     - "3000:8080"
   restart: unless-stopped
   volumes:
    - api:/usr/src/app/
   depends_on: 
     - postgres
   environment: 
    POSTGRES_URL: postgres:5432
   networks: 
     - gin-rest-api-net
    
   # Postgres Service
 postgres:
   image: postgres:12-alpine
   container_name: gin_rest_api_db
   environment:
    - POSTGRES_USER=${DB_USER}  
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - POSTGRES_DB=${DB_NAME}
    - DATABASE_HOST=${DB_HOST} 
   ports:
   - "5432:5432"
   volumes:
   - postgres_data:/var/lib/postgresql/data
   restart: unless-stopped
   networks: 
    - gin-rest-api-net
  
volumes:
  api:
  postgres_data:       
  # Networks for communication between containers      
networks: 
    gin-rest-api-net:
      driver: bridge